### ISSUE TITLE
Doesn't run anymore on Windows 10

### ISSUE THREAD

**Issue by Gorrekun** [ScottyDoesKnow/DS3Backup#1]
Trying to run the program simply doesn't do anything, not any error or message. It stopped working since March for me.

**Comment by ScottyDoesKnow** [comment]
Just released a new version that adds an error handler to the startup, try it out and see if it gives you more info.

**Comment by Gorrekun** [comment]
There you go: https://gyazo.com/b95eee915c00e8b813f8b86b5941a062

**Comment by ScottyDoesKnow** [comment]
Looks like the settings got screwed up somehow. If you go to %AppData%\DS3Backup there should be a settings file and a settings.bak file. You can try replacing the .settings with the .settings.bak file or just deleting the .settings file and running again.

**Comment by Gorrekun** [comment]
Deleting the settings fixed it for me, thanks bunches for this awesome tool!

**Comment by ScottyDoesKnow** [comment]
No worries, I mostly just made it for myself so glad some people are finding it useful.
